apiVersion: v1
kind: Service
metadata:
  name: todo-list-service-preview
  labels:
    app: todo-list-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: todo-list-service
  type: NodePort
