apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-list-service
    version: 1.0.1
    env: dev
  name: todo-list-deployment
  namespace: todo-list-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list-service
  strategy: {}
  template:
    metadata:
      labels:
        app: todo-list-service
        api: downward
        usage: global
        env: dev
        version: 1.0.1
    spec:
      containers:
        - name: app
          image:  jojovem/todo-list-service:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "512m"
            limits:
              memory: "4096Mi"
              cpu: "1024m"
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
