apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
  - target:
      kind: Rollout
      name: rollout-todo-list-service
    path: ./cpu_count.yaml
  - target:
      kind: Rollout
      name: rollout-todo-list-service
    path: ./replica_count.yaml
