apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-deployment
  namespace: todo-list-service
spec:
  template:
    spec:
      containers:
        - name: todo-list-service-container
          resources:
            requests:
              cpu: "512m"
            limits:
              cpu: "1024m"
