apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-preview
  labels:
    app: {{ .Values.app.name }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.app.name }}
  type: NodePort
