replicaCount: 2
image:
  repository: jojovem/todo-list-service
  tag: 1.0.3
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
app:
  name: "todo-list-service2"
  namespace: "todo-list"
