apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-list-service
    version: 1.0.0
    env: dev
  name: todo-list-deployment
  namespace: todo-list-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list-service
  strategy: {}
  template:
    metadata:
      labels:
        app: todo-list-service
        api: downward
        usage: global
        env: dev
        version: 1.0..0
    spec:
      containers:
        - name: app
          image:  todo-list-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nod eName