apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
  strategy:
    canary:
      canaryService: {{ .Values.app.name }}-preview
      stableService: {{ .Values.app.name }}-active
      maxSurge: "25%"
      maxUnavailable: 0
      trafficRouting:
        nginx:
          stableIngress: todo-list-service-ingress
          additionalIngressAnnotations:   # optional
            canary-by-header: X-Canary
            canary-by-header-value: iwantsit
      steps:
        - setWeight: 10
        - pause: {} # pause indefinitely
        - setWeight: 20
        - pause: {} # pause indefinitely
{{/*    blueGreen:*/}}
{{/*      autoPromotionEnabled: false*/}}
{{/*      activeService: {{ .Values.app.name }}-active*/}}
{{/*      previewService: {{ .Values.app.name }}-preview*/}}
