apiVersion: v1
kind: Service
metadata:
  labels:
    app: preview-todo-list-service
  name: preview-todo-list-service
  namespace: todo-list
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: todo-list-service
    version: 1.0.6
  type: NodePort
