apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: todo-list-service
    version: 1.0.5
  name: todo-list-rollout
  namespace: todo-list
spec:
  replicas: 4
  selector:
    matchLabels:
      app: todo-list-service
  strategy:
    canary:
      steps:
        - setWeight: 20
        # The following pause step will pause the rollout indefinitely until manually resumed.
        # Rollouts can be manually resumed by running `kubectl argo rollouts promote ROLLOUT`
        - pause: {}
        - setWeight: 40
        - pause: {duration: 40s}
        - setWeight: 60
        - pause: {duration: 20s}
        - setWeight: 80
        - pause: {duration: 20s}
  template:
    metadata:
      labels:
        app: todo-list-service
        version: 1.0.5
    spec:
      containers:
        - name: todo-list-service-container
          imagePullPolicy: Always
          image: jojovem/todo-list-service:1.0.5
          resources:
            requests:
              memory: "512Mi"
              cpu: "512m"
            limits:
              memory: "4096Mi"
              cpu: "1024m"
