apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-list-service
  name: todo-list-service
  namespace: todo-list
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
  selector:
    app: todo-list-service
    version: 1.0.1
  type: NodePort
