apiVersion: v1
kind: Service
metadata:
  name: todo-list-service
  namespace: todo-list
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: rollout-todo-list-service
  type: NodePort
